services:
  app:
    image: ghcr.io/nooblk-98/production-laravel:production
    container_name: production-laravel-app
    expose:
      - "80"
    volumes:
      - /var/www/application/storage:/var/www/html/storage
      - /var/www/application/.env:/var/www/html/.env
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    external: true
