name: Deploy to production server

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          PROJECT_NAME=$(basename ${{ github.repository }})
          docker build \
            -f ./Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:production \
            -t ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          PROJECT_NAME=$(basename ${{ github.repository }})
          docker push ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:production
          docker push ghcr.io/${{ github.repository_owner }}/${PROJECT_NAME}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Compose Deploy"
        uses: cssnr/stack-deploy-action@v1
        with:
          name: "sample-application"
          file: "docker/production/docker-compose.yml"
          registry_host: "ghcr.io"
          registry_user: ${{ secrets.GHCR_USER }}
          registry_pass: ${{ secrets.GHCR_PASS }}
          host: ${{ secrets.DOCKER_HOST }}
          port: ${{ secrets.DOCKER_PORT }}
          user: ${{ secrets.DOCKER_USER }}
          ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
          prune: true
          mode: compose
          args: --remove-orphans --force-recreate --pull always

  # create-release:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - uses: marvinpinto/action-automatic-releases@latest
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         automatic_release_tag: "v1.0.${{ github.run_number }}"
  #         title: "Release for commit ${{ github.sha }}"

#   clean:
#     runs-on: ubuntu-latest
#     needs: create-release
#     name: clean
#     steps:
#       - uses: snok/container-retention-policy@v3.0.0
#         with:
#           account: weblankan-lk
#           token: ${{ secrets.GITHUB_TOKEN }}
#           image-names: ${{ env.project_name }}
#           cut-off: 7d
#           keep-n-most-recent: 5
#           dry-run: false